version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: flask run --host=0.0.0.0 --port=5000
    # or use CMD from Dockerfile (gunicorn) in production

volumes:
  db_data:
